// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  bio: dynamic(() => import("./Bio")),
  bp_content: dynamic(() => import("./BpContent")),
  heroname: dynamic(() => import("./Heroname")),
  tech_block: dynamic(() => import("./TechBlock")),
};
